In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Play_Tennis.csv')

In [3]:
df.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

Training

Look table (Dictionary)

Testing

P(Yes)

P(No)

In [5]:
df['Play Tennis'].value_counts()

Play Tennis
Yes    9
No     5
Name: count, dtype: int64

In [6]:
py = 9/14
pn = 5/14

In [7]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [9]:
# Outlook

pd.crosstab(df['Outlook'], df['Play Tennis'])

Play Tennis  No  Yes
Outlook
Overcast      0    4
Rain          2    3
Sunny         3    2

In [10]:
P_overcast_n = 0
P_Rain_n = 2/5
P_Sunny_n = 3/5

P_overcast_y = 4/9
P_Rain_y = 3/9
P_Sunny_y = 2/9

In [12]:
# Temp

pd.crosstab(df['Temperature'], df['Play Tennis'])

Play Tennis  No  Yes
Temperature
Cool          1    3
Hot           2    2
Mild          2    4

In [13]:
P_Cool_n = 1/5
P_Hot_n = 2/5
P_Mild_n = 2/5

P_Cool_y = 3/9
P_Hot_y = 2/9
P_Mild_y = 4/9

In [14]:
# Humidity

pd.crosstab(df['Humidity'], df['Play Tennis'])

Play Tennis  No  Yes
Humidity
High          4    3
Normal        1    6

In [15]:
P_High_n = 4/5
P_Normal_n = 1/5

P_High_y = 3/9
P_Normal_y = 6/9

In [16]:
# Wind

pd.crosstab(df['Wind'], df['Play Tennis'])

Play Tennis  No  Yes
Wind
Strong        3    3
Weak          2    6

In [17]:
P_Strong_n = 3/5
P_Weak_n = 2/5

P_Strong_y = 3/9
P_Weak_y = 6/9

#### Problem 1 

Outlook = Sunny, Temp = Hot, Humidity = High, Wind = Weak

Play or No Play ?

#### Solution

P(Yes | Sunny, Hot, High, Weak) = P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes)

P(No | Sunny, Hot, High, Weak) = P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No)

Compare using Maximum Posteriori Rule

In [21]:
P_Yes = py * P_Sunny_y * P_Hot_y * P_High_y * P_Weak_y 
print(P_Yes)

0.007054673721340388

In [20]:
P_No = pn * P_Sunny_n * P_Hot_n * P_High_n * P_Weak_n
print(P_No)

0.02742857142857143

### Result

No Play 

As P_No > P_Yes

#### Problem 2

Outlook = Overcast, Temp = Cold, Humidity = Low, Wind = Weak

Play or No Play ?

#### Solution

P(Yes | Overcast, Cold, Low, Weak) = P(Overcast | Yes) * P(Cold | Yes) * P(Low | Yes) * P(Weak | Yes)

P(No | Overcast, Cold, Low, Weak) = P(Overcast | No) * P(Cold | No) * P(Low | No) * P(Weak | No)

Compare using Maximum Posteriori Rule

In [22]:
P_Yes = py * P_overcast_y * P_Cool_y * P_Normal_y * P_Weak_y 
print(P_Yes)

0.042328042328042326

In [24]:
P_No = pn * P_overcast_n * P_Cool_n * P_Normal_n * P_Weak_n
print(P_No)

0.0

### Result

Play

As P_Yes > P_No